# -*- coding: utf-8 -*-
"""Atividade 07 - PVI - Numérico

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uBhMc3IXjTGwrEmetIpvcLefx38QtUFh
"""

import numpy as np
import matplotlib.pyplot as plt

# Parâmetros do modelo SIR
beta = 0.4
gamma = 0.035
N = 1000

# Condições iniciais
S0 = 990
I0 = 10
R0 = 0

# Tempo de simulação e passo
h = 0.1
t_total = 60
n_steps = int(t_total / h)

# Função do sistema SIR
def sir_model(t, y):
    S, I, R = y
    dSdt = -(beta / N) * S * I
    dIdt = (beta / N) * S * I - gamma * I
    dRdt = gamma * I
    return np.array([dSdt, dIdt, dRdt])

# Método de Runge-Kutta de ordem 4
def runge_kutta_4(f, t, y, h):
    k1 = f(t, y)
    k2 = f(t + h/2, y + h/2 * k1)
    k3 = f(t + h/2, y + h/2 * k2)
    k4 = f(t + h, y + h * k3)
    return y + (h/6) * (k1 + 2*k2 + 2*k3 + k4)

# Inicializando os resultados
results = np.zeros((n_steps + 1, 3))
results[0] = [S0, I0, R0]
times = np.linspace(0, t_total, n_steps + 1)

# Simulação do sistema SIR usando RK4
for i in range(n_steps):
    t = times[i]
    results[i+1] = runge_kutta_4(sir_model, t, results[i], h)

S = results[:, 0]
I = results[:, 1]
R = results[:, 2]

plt.figure(figsize=(10,6))
plt.plot(times, S, label='Suscetíveis (S)')
plt.plot(times, I, label='Infectados (I)')
plt.plot(times, R, label='Recuperados (R)')
plt.xlabel('Tempo (dias)')
plt.ylabel('Número de pessoas')
plt.title('Modelo SIR - Dinâmica da epidemia')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# O pico da epidemia é quando tem mais infectados ao mesmo tempo
pico_idx = np.argmax(I)
pico_t = times[pico_idx]
pico_I = I[pico_idx]

# Aqui a gente vê quando o número de infectados fica menor que 1, ou seja, quando a epidemia praticamente acabou
controlada_idx = np.where(I < 1)[0]
if len(controlada_idx) > 0:
    t_controlada = times[controlada_idx[0]]
else:
    t_controlada = None

# Comentários:
# - O pico dos infectados acontece em pico_t dias, com pico_I pessoas doentes ao mesmo tempo.
# - A epidemia fica "controlada" quando o número de infectados cai para menos de 1, o que acontece em t_controlada dias (se isso acontecer nos 60 dias simulados).
# - No gráfico dá pra ver direitinho: os suscetíveis vão caindo, os infectados sobem até o pico e depois caem, e os recuperados só aumentam.
# - O modelo mostra que o pico não é o fim: depois dele ainda tem muita gente ficando doente, mas a situação vai melhorando até quase todo mundo estar recuperado.