# -*- coding: utf-8 -*-
"""Atividade 04 - Interpolação Polinomial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQol26qwrvATojzGHQG_5bXuDviLiQiA

Considere a tabela a seguir que relaciona o calor específico da água com a temperatura:

| Temperatura (°C) | Calor Específico |
|------------------|------------------|
| 30              | 0.99826          |
| 35              | 0.99818          |
| 40              | 0.99828          |
| 45              | 0.99849          |

### Problemas a Resolver

1️⃣ **Interpolação Polinomial para Determinar o Calor Específico**  
Determine o calor específico da água a **37.5°C** utilizando interpolação polinomial. Construa um polinômio \( p(x) \) de grau três e calcule \( p(37.5) \).

2️⃣ **Determinação da Temperatura para um Calor Específico Específico**  
Calcule a temperatura em que o calor específico é **0.99837**, utilizando o polinômio obtido no item anterior. Para isso, encontre numericamente a raiz de $ p(x) = 0.99837$ aplicando o método da **bissecção**, garantindo um erro menor que $( 10^{-6} )$
"""

import numpy as np
from numpy.polynomial.polynomial import Polynomial

#dados de entrada (temperatura vs calor específico)
temperaturas = np.array([30, 35, 40, 45])
calores = np.array([0.99826, 0.99818, 0.99828, 0.99849])

#cria polinômio interpolador de grau 3 usando numpy
polinomio = Polynomial.fit(temperaturas, calores, 3)

#cálculo para 37.5°c
calor_37_5 = polinomio(37.5)
print(f"calor específico a 37.5°c: {calor_37_5:.5f}")

def bisseccao(f, a, b, tol=1e-6):
    #verifica troca de sinal no intervalo inicial
    fa, fb = f(a), f(b)
    if fa * fb > 0:
        return None

    #loop até atingir a precisão desejada
    while (b - a)/2 > tol:
        c = (a + b) / 2  # ponto médio
        fc = f(c)

        #decide qual subintervalo contém a raiz
        if fc == 0:
            return c
        elif fa * fc < 0:
            b, fb = c, fc
        else:
            a, fa = c, fc

    return (a + b)/2  # retorna a aproximação final

#função para encontrar a raiz: p(x) - 0.99837 = 0
f = lambda x: polinomio(x) - 0.99837
raiz = bisseccao(f, 30, 45)

print(f"temperatura correspondente: {raiz:.5f}°c")